error if the given style is not found

diff --git a/tasks/bake-book.yml b/tasks/bake-book.yml
--- a/tasks/bake-book.yml
+++ b/tasks/bake-book.yml
@@ -22,9 +22,12 @@ run:
       cp -r assembled-book/* baked-book
       book_dir="baked-book/$(cat book/name)"
       cnx-easybake "cnx-recipes/recipes/output/$(cat book/recipe).css" "$book_dir/collection.assembled.xhtml" "$book_dir/collection.baked.xhtml"
-      style_file="cnx-recipes/styles/output/$(cat book/name)-pdf.css"
+      style_file="cnx-recipes/styles/output/$(cat book/style)-pdf.css"
       if [ -f "$style_file" ]
       then
         cp "$style_file" $book_dir
         sed -i "s%<\\/head>%<link rel=\"stylesheet\" type=\"text/css\" href=\"$(basename $style_file)\" />&%" "$book_dir/collection.baked.xhtml"
+      else
+        echo "Style Not Found" >baked-book/stderr
+        exit  1
       fi
